### ISSUE TITLE
ChatGPT 的微信 Bot 

### ISSUE THREAD

**Issue by devalin** [Kamigami55/awesome-chatgpt#1]
from https://twitter.com/fuergaosi/status/1600123393541828608

ChatGPT 的微信 Bot ,裝完依賴後只需要填寫 OpenAI 帳號密碼和微信掃碼就可以使用

https://github.com/fuergaosi233/wechat-chatgpt

**Comment by Kamigami55** [comment]
謝謝提供！已新增～
Thanks for the contribution! Added to the list.
https://github.com/Kamigami55/awesome-chatgpt/commit/8b8cb89db0062c47f37e10d2678a13de0f5a0bdb
