### ISSUE TITLE
ChatGPT 指令大全

### ISSUE THREAD

**Issue by wastu01** [Kamigami55/awesome-chatgpt#10]
link : [https://www.explainthis.io/zh-hant/chatgpt](https://www.explainthis.io/zh-hant/chatgpt)

**Comment by Kamigami55** [comment]
Thank you! Added in the list! (commit: https://github.com/Kamigami55/awesome-chatgpt/commit/e10bc7ef625bf00d2f340ab1683c309b5ff0b519)
