### ISSUE TITLE
Add ChatMind - Generating and Modifying Mind Maps through AI Dialogue

### ISSUE THREAD

**Issue by shitianfang** [Kamigami55/awesome-chatgpt#12]
Add ChatMind - Generating and Modifying Mind Maps through AI Dialogue

https://www.chatmind.tech/

**Comment by eason-dev** [comment]
Thank you! It's a cool project! Added in the list. (commit: https://github.com/Kamigami55/awesome-chatgpt/commit/e4658eb82629c92b75f1e25d3fceb7b9fb1cd73c)
